### ISSUE TITLE
When not-logged-in redirects to login without allowing anonymous landing page

### ISSUE THREAD

**Issue by jpinkham1** [rbrki07/hilla-oauth-authorization-code-flow-keycloak#1]
I was happy to find this project to get me started with hilla and keycloak.  It worked great.

Because the / route is marked as 'requiresLogin: true' in routes.tsx, it went immediately to the keycloak login.  For the same reason, when I hit the sign-out button, it also redirected to the login.  

This makes sense but **I want to defer login and allow some landing page behavior/info so that login is deferred** until they try to visit a route that requires login.

To have a public landing page, I changed routes.tsx#16 to make requiresLogin: false for the / route.

However, this did not have the expected effect; the **redirect to login behavior continued** as before at both startup and sign-out.

I also noticed and fixed a nullPointer in SecurityConfig.userAuthoritiesMapper when the userInfo.getClaim("roles") for the not-logged-in userInfo returned a null instead of an empty collection.  I don't think this was related to the login redirect behavior.

**I'd love to hear any suggestions** regarding the ability to allow anonymous access.

Meanwhile, here is my proposed fix for the NPE when a user (or no user) has null list of roles:

```
import java.util.Collection;
import java.util.Objects;
```
...
```
    GrantedAuthoritiesMapper userAuthoritiesMapper() {
        return (authorities) -> {
            return authorities.stream()
                    .filter(OidcUserAuthority.class::isInstance)
                    .map(authority -> {
                                OidcUserAuthority oidcUserAuthority = (OidcUserAuthority) authority;
                                OidcUserInfo userInfo = oidcUserAuthority.getUserInfo();
                                return (Collection<String>) userInfo.getClaim("roles");
                            })
                    .filter(Objects::nonNull)
                    .flatMap(Collection::stream)
                    .map(SimpleGrantedAuthority::new)
                    .collect(Collectors.toList());
        };
    }
```

Sincerely,
Jim Pinkham
Columbus OH

Also, P.S.
When first ran it (focused on setting the correct client-secret set in my config/local application.properties) I was getting errors in keycloak "type="CODE_TO_TOKEN_ERROR" and 'too many redirects' in the app.  I was able to get past that by marking the hilla client as public (uncheck the Client Authentication checkbox in the hilla client capability config section).  But later, I spotted a typo in the **property name** (I had somehow introduced) for the client-secret and when I fixed that, it worked fine.  Hope that helps someone else.

**Comment by rbrki07** [comment]
Hello @jpinkham1,
thank you for reading my blog post, trying the example and your kind words. I'm happy to hear that it was helpful for you. 

To make "/" accessible for unauthenticated users, you also have to change the `SecurityConfig`:
```java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeHttpRequests(authorize ->
                authorize.requestMatchers(
                        new AntPathRequestMatcher("/")
                ).permitAll()
        );
        super.configure(http);
        setOAuth2LoginPage(http, "/oauth2/authorization/keycloak");
        http.logout(logout -> logout.logoutSuccessHandler((new HttpStatusReturningLogoutSuccessHandler(HttpStatus.OK))));
    }
```

Adding a request matcher for path "/" and setting it to `permitAll()` makes it accessible for unauthenticated users. I hope this is what you are trying to achieve.

**Comment by jpinkham1** [comment]
Rene,

Thanks so much for that tip - that's exactly what I needed for anonymous
access for both "/" and things like "/images/*" ...etc.

There may still be another problem though.  I made that null check "fix" at
first because I thought the lack of "roles" claim was due to not being
logged in, but even when logged in as one of the test users with IC or
MANAGER role, the claim still isn't there, so perhaps there's something
else wrong (and explaining why you didn't already have that case handled).
There must be a problem with the mapper.  I've re-built the client several
times to be sure I'm following every step, but either I'm just not seeing
something or maybe there's something changed with newer versions (for
example, I'm using Keycloak 25.0.0  and it rejected username jd as being
too short so that's why it's jdoe2).

When I print the claims map, I get, for example:
{sub=ed70a72b-390b-4ba3-95ba-34851fa99b05, email_verified=true, name=Jane
Doe, preferred_username=jdoe2, given_name=Jane, family_name=Doe, email=
***@***.***}

where I'd have expected to see an entry for , roles=["ROLE_MANAGER"]

I've attached a json export of my hilla client - if you have yours handy,
perhaps there's a difference you see?
The only strange thing I notice is an user.attribute name of "foo" which I
can't see anyplace in the keycloak UI.

Thanks again,
Jim

**Comment by rbrki07** [comment]
Hi Jim,
difficult to say what the problem could be. I'm using Keycloak 24.0.4.
Two thoughts:
* In "Clients" (hilla) > "Client details" > "Client scopes" (hilla-dedicated) > "Mappers" (client roles) it is important to activate "Add to userinfo".
* In "Clients" (hilla) > "Client details" > "Client scopes" you can select the tab "Evaluate". Here you can select a user and you will see the generated user info that should look like this:
```json
{
  "sub": "ee3660b3-c4c8-4b93-b1ff-0550ec14f1fe",
  "email_verified": true,
  "roles": [
    "ROLE_IC"
  ],
  "name": "John Doe",
  "preferred_username": "jd",
  "given_name": "John",
  "family_name": "Doe",
  "email": "john.doe@example.com"
}
```

I attached a realm export of my local test keycloak. You could have a look at that and compare it with yours or import it to your local keycloak instance. 
[realm-export.json](https://github.com/user-attachments/files/16113327/realm-export.json)

**Comment by jpinkham1** [comment]
Rene,

Thanks again!  Your realm-export helped me notice that the new version of
keycloak must have introduced an error.

In my version the usermodel.clientRoleMapping.clientId was a uuid and in
yours the value was just the client name "hilla".

      "protocolMappers": [
        {
          "id": "0e198163-c2f6-4d3d-9ac0-d1f40747b6ec",
          "name": "client roles",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usermodel-client-role-mapper",
          "consentRequired": false,
          "config": {
            "usermodel.clientRoleMapping.rolePrefix": "ROLE_",
            "introspection.token.claim": "true",
            "multivalued": "true",
            "userinfo.token.claim": "true",
            "user.attribute": "foo",
            "id.token.claim": "false",
            "lightweight.claim": "false",
            "access.token.claim": "true",
            "claim.name": "client_roles",
            "jsonType.label": "String",
            "usermodel.clientRoleMapping.clientId":
"9d213ac8-52f4-46a2-87c0-f1133132ba0f"
          }
        },

So I edited my export file to use the client name instead, deleted the
hilla client, and then used the import feature instead of using the UI to
re-create it (I had to re-create and assign the roles to the users again
too), and now it all works fine!

Sorry to have bothered you, but I wanted to let you know how much that
helped.

I'll probably just downgrade back to 24.0.4 to really avoid the issue!

Sincerely,
Jim

**Comment by rbrki07** [comment]
Glad I could help you, Jim!
